version: '2'

services:
  v2pneudb:
    image: mysql
    container_name: v2pneudb
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "3380:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=v2pneu
      - MYSQL_PASSWORD=v2pneu
      - MYSQL_DATABASE=v2pneu
      - MYSQL_USER=v2pneu
